### PR TITLE
Improve style of status view

### PR DESCRIPTION
**Pull request by lumnn**
Developed for myself, but I thought I share, maybe you'll use some parts of this code.

Changes:
   - non staged lines start with white space instead of empty box
   - staged lines are bold
   - separator line and keybinding description is less visible
   - file path have focus on filename and it's colour depends on type of change, the path is less visible

peek 2019-02-27 10-24

### CODE REVIEW

**Comment by predragnikolic** [comment]
This is a question of personal taste. :)

While I can see that some people would like this (colored file names),
on the other hand, I am happy with how it currently looks (only the modification type is colored, and the file name is not).

One option is to make an optional bool setting `color_file_name` that would allow for that, so both sides are happy. What do you think about that?

**Comment by lumnn** [comment]
That's what I thought - not everyone may like it. I worked on a project with nested files, to I thought it may help me to find the files I want.

Setting feels the best. I'll try implementing it once I have some spare time. Although I don't promise best code as I'm new to python

**Comment by predragnikolic** [comment]
Take you time 
Not that somebody is paying you for this :-D

Don't worry. This repository was written while I was new to python and the sublime API, so feel right at home.

**Comment by lumnn** [comment]
Hi @predragnikolic 
I updated PR to include settings for file list theme and symbol indicating file is tracked.

PR also removes character before untracked files. It was easier for me to work with custom theme and also it made it simpler to allow custom symbol for tracked files

**Comment by predragnikolic** [comment]
@lumnn Sorry that it took so long to realize that you changes are great :)

**Pull request merged**
